---
- name: Install IDG packages using dnf module
  ansible.builtin.dnf:
    name:
      - /tmp/idg_lx{{ version }}.{{ edition }}.common.x86_64.rpm
      - /tmp/idg_lx{{ version }}.{{ edition }}.{{ mode }}.image.x86_64.rpm
    state: present
    disable_gpg_check: true 
  become: true
