---
- name: Start the datapower service
  ansible.builtin.systemd:
    name: datapower
    state: restarted
    enabled: yes
  become: true

- name: Run systemctl status datapower
  ansible.builtin.command:
    cmd: systemctl status datapower
  register: datapower_status_result 
  changed_when: false
  become: true

- name: Print the service status
  ansible.builtin.debug:
    msg: "{{ datapower_status_result.stdout_lines }}"
