---
- hosts: "{{ ansible_play_hosts }}"
  become: true
  vars:
    version: 10650
    edition: cd
    mode: nonprod
    standby_control: false
    raid_device: /dev/vdb
    cpu_limit: 4
    memory_limit: 8192
    config_dir: /datapower/config
    local_dir: /datapower/local
    image_size: 16G
    epel: false
  roles:
    - installprereqs
    - role: copyfile
      vars:
        src_file_path: /root/downloads/idg/idg_lx{{ version }}.tar
        dest_file_path: /tmp/idg_lx{{ version }}.tar
    - installdp
    - configuredp
    - startdp
